Lambda-School-Labs/human-rights-first-police-ds-a

confirmed_cases.csv
edited csv on confirmed cases on the human rights first website
=> edited csv on confirmed cases on the human rights first website

notebooks/labs34_notebooks/confirmed_test.ipynb
initial .ipynb for cleaner data,
CSV uploaded.
=> first PR for cleaner data team A

notebooks/labs34_notebooks/unconfirmed.ipynb
I created a dataset of unconfirmed police incidents. These are tweets that discuss about racism and police violence without being reports of specific incidents. This was imported as a csv file then converted into a pandas dataframe in the unconfirmed ipynb file
=> added unconfirmed dataset and put it into pandas dataframe

notebooks/labs34_notebooks/twitter_geocode.ipynb, notebooks/labs34_notebooks/twitter_reply.ipynb
Joan - notes on twitter reply functionality
Description: 
=> twitter bot reply notes

app/TagList.py, app/TagMaker.py
Description: 
The data is inconsistently tagged. The TagMaker class can be used to uniformly create tags across all existing and incoming data in the database. It has been tested with current tags, stored in TagList.py. These tags can easily be updated in the future.
TagList.py, a file containing a list of currently used tags was added. TagMaker.py, a file containing a new class that can use the tag list and any string text to create a list of tags that can be found in the text.
=> Class to create tags for data. Co-authored by Nico C and Anas A

app/create_db_tables.py
=> Modified table name from in_process to twitter_potential_incidents.

app/TagMaker.py
=> Improved tagmaker efficiency. Coauthored by Nico C.

app/create_db_tables.py
=> updated the tables for easy comprehension

app/create_db_tables.py, app/helper_funcs.py, app/scraper.py
Description: 
Table schemas needed small change and ranks were not consistent throughout tables
Table column names were renamed or removed, a rank dictionary was added to convert rank integers into descriptive text
=> Fixed long/lon typos, finalized table schemas/added rank dictionary

app/twitter_bot.py, notebooks/labs34_notebooks/twitter_bot_test.ipynb
=> twitter bot test notebook

Pipfile, app/twitter_bot.py
=> Edit pipfile

app/create_db_tables.py, app/scraper.py
=> Changed schema to be consistent with new tables

known_defects_labs_34.md
=> updated known defects

app/scraper.py
Naming: feature/feature-connect-scraper-heroku/hillaryk
Reviewers: minimum 2 (TPL and/or 2 from Web or DS respectively and not person who submitted PR)
Description: 
- Team wanted to connect scraper data originally linked to the sandbox environment (ElephantSQL) to staging environment 
(Heroku)
- DS team updated scraper.py to use the Heroku credentials for the database instead of the original ElephantSQL database
- DS updated table to be 'twitter_incidents_new' on Heroku instead of 'incidents' on ElephantSQL
- DS team updated the SQL code to push to 'twitter_incidents_new' table on Heroku instead of 'incidents' table on ElephantSQL
=> connects data from scraper to heroku database (originally connected to sandbox ElephantSQL)

.gitattributes, app/frankenbert.py, app/helper_funcs.py, app/pytorch_load.ipynb, app/scraper.py
Naming: new_bert_model_implementation
Description: 
- The Twitter scraper was originally connected to an older version of the BERT model through an API hosted on AWS. We decided to make this more efficient by removing the use of an extra API and allowing the scraper to access the model in a local environment.
- To establish a local connection we needed to change a few files:
- First, we added frankenbert.py to store the FrankenBert class that allows us to load a serialized BERT model and make predictions on scraped Twitter data.
-  Second, we imported the FrankenBert class to the scraper.py file and replaced the old …
=> Establishes local connection to retrained BERT model

README.md, newREADME.md
Naming: labs36-readme-edits
Description: 
- As the project comes to a close, labs36 updated the readmes to reflect changes in our codebase from the last month.
- The repo now holds our newer codebase but keeps the old codebase in a separate folder - we updated the readme associated with that old codebase to reflect contributions we made in the last month
- Added a new readme for the new codebase - contains update links to our API, labs36 contributions, and additional steps for how to use a requirements.txt to deploy our app locally.
=> Updates old readme and creates new one for updated codebase

README.md
Naming: final-edits
Description: 
- To polish documentation on the repo before handing it off to stakeholder or another team
- Re-organizes readme to have Overview, Features, Next Steps, Contributors, and Getting Started sections
- Edits language throughout for clarity
- Fixes grammatical errors
=> Makes small edits for clarity in main readme 

notebooks/labs37_notebooks/FrankenBert.ipynb
=> Needed to remove the DB url from the notebook

Pipfile, README.md
=> Adjusting our contributor frames

app/main.py
=> 'keywords'

app/main.py
=> fixed a bug in the API regarding symbols in URLs in GET requests

app/main.py
Naming: feature - Expanded the search terms for the scraper
Description: 
Improve the search capabilities of the scraper to ensure it encapsulates most terms related to police brutality.
Added to the current list of search keywords.
=> Andrew Haney

.ebignore, app/main.py, post_tests.py
Reviewers: minimum 2 (Ryan and/or 2 from Web or DS respectively and not a person who submitted PR)
Description: 
We're about to deploy our retrained BERT model
Removing .text from user_input and adding more files to ebignore
=> Preparing for deployment

notebooks/labs37_notebooks/FrankenBERT_Labs37.ipynb
Naming: feature/description-name
FrankenBert retrained
Reviewers: Minimum 2 (Ryan, Josh, and/or Imani and/or 2 from WEB or DS respectively and not the person who submitted the PR)
Description: 
What is the motivation for these changes?
Completed Notebook
Bert has been retrained on data
- [ * ] Small scope (1-2 components/code cells/functions)
- [ *] Not too many concerns in a single commit
- [ *] Removed extraneous comments (DB_URL, code in comments, print statements, to-dos, console.logs, extra fluff)
- [ *] Atomic, descriptive commit messages
- [* ] Consistent formatting
=> retrained Bert

app/bot.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
=> final commit for bot deployment

app/bot.py, app/db.py, app/twitter.py
Co-authored-by: Chris <chris-chilton@hotmail.com>
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
This bug fix ensures that the advance all API call, progresses the conversation by one step and updates the conversations table accordingly. 
video [link](https://www.loom.com/share/0588e222cf954bb29e50989c902bfff2)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
This bug was tested by progressing through a conversation on a local set-up
- [x ] Test A
**Test Configuration**:
* Firmware version:
* …
=> fixed advanced all bug, by inserting proper status to database

app/main.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
=> pep8 fixes and cleanup
